---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: myblue
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/sericea-main
image-version: latest

modules:
  - from-file: default-rpms.yml
  - from-file: default-flatpaks.yml
  - from-file: ghostty.yml
    
  - type: files
    files:
      - source: system
        destination: /

  - type: brew

  - type: signing
