# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: myblue
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - from-file: modules/default_flatpaks.yml
  - from-file: modules/default_rpms.yml
  - from-file: modules/gnome_extentions.yml
  - from-file: modules/gnome_flatpaks.yml
  - from-file: modules/gnome_rpms.yml
  - from-file: modules/ghostty.yml
  - from-file: modules/sway.yml
    
  - type: files
    files:
      - source: system
        destination: /

  - type: signing
