- type: default-flatpaks
  notify: true
  system:
    install:
      - io.github.dvlv.boxbuddyrs      # BoxBuddy
      - com.brave.Browser              # Brave Browser
      - org.fedoraproject.MediaWriter  # Fedora Media Writer
      - com.github.tchx84.Flatseal     # Flatseal
      - io.gitlab.librewolf-community  # LibreWolf Browser
      - io.github.flattool.Warehouse   # Warehouse
  user: {}

- type: rpm-ostree
  install:
    - git
    - git-delta
    - google-droid-fonts-all
    - google-noto-fonts-all
    - google-noto-emoji-fonts
    - google-noto-color-emoji-fonts
    - stow
    - papirus-icon-theme
    - papirus-icon-theme-dark
    - yaru-icon-theme
  remove:
    - firefox
    - firefox-langpacks
    - ptyxis
